# This is a basic workflow to help you get started with Actions

name: CMSIS-Pack

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: Checkout sources recursively
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.REPO_SCOPED_TOKEN }}
        submodules: true

    # Generate CMSIS-Pack
    - name: Generate CMSIS-Pack
      run: |
        echo setup environment and install tools.
        sudo apt-get update
        sudo apt-get install p7zip-full curl libxml2-utils
        mkdir -p $HOME/Arm/Packs/ARM/CMSIS/5.9.0
        wget https://github.com/ARM-software/CMSIS_5/releases/download/5.9.0/ARM.CMSIS.5.9.0.pack
        unzip -q ARM.CMSIS.5.9.0.pack -d $HOME/Arm/Packs/ARM/CMSIS/5.9.0
        rm ARM.CMSIS.5.9.0.pack
        export CMSIS_PACK_ROOT=$HOME/Arm/Packs
        export PATH=$PATH:$HOME/Arm/Packs/ARM/CMSIS/5.9.0/CMSIS/Utilities/Linux64
      
        echo generate cmsis-pack.
        cd cmsis_pack
        chmod a+x ./run.sh
        chmod a+x ./gen_pack.sh
        ./run.sh
        cd ..

    - name: Publish Pipeline Artifact
      uses: actions/upload-artifact@v3
      with:
        name: cmsis_pack
        path: |
          ./cmsis_pack/output




